module.exports = [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      '*.min.js',
      'eslint.config.js',
    ],
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        localStorage: 'readonly',
        CustomEvent: 'readonly',
        // IndexedDB
        indexedDB: 'readonly',
        IDBKeyRange: 'readonly',
        // Canvas API
        CanvasRenderingContext2D: 'readonly',
        // External libraries
        html2canvas: 'readonly',
        // Custom globals from other scripts
        getDayLog: 'writable',
        saveDayLog: 'writable',
        deleteDayLog: 'writable',
        getDayLogsByWeek: 'writable',
        getAllDayLogs: 'writable',
        getWeekTarget: 'writable',
        saveWeekTarget: 'writable',
        deleteWeekTarget: 'writable',
        getAllWeekTargets: 'writable',
        getISOWeekInfo: 'writable',
        // Date utilities (from date-utils.js)
        formatDateLocal: 'writable',
        parseDateLocal: 'writable',
        // Constants (from constants.js)
        DAY_NAMES_JP: 'readonly',
        DAY_NAMES_EN: 'readonly',
        DAY_LABELS_CHART: 'readonly',
        DAY_NAME_JP_TO_EN: 'readonly',
        MS_PER_WEEK: 'readonly',
        MS_PER_DAY: 'readonly',
        MAX_DAYS_HISTORY: 'readonly',
        CHART_PADDING: 'readonly',
        CHART_BAR_WIDTH_RATIO: 'readonly',
        Y_AXIS_CONFIG: 'readonly',
        CHART_GRID_LINES: 'readonly',
        ELEVATION_INPUT: 'readonly',
        WEEKLY_TARGET_INPUT: 'readonly',
        BACKUP_CONFIG: 'readonly',
        ISO_YEAR_RANGE: 'readonly',
        ISO_WEEK_RANGE: 'readonly',
        // Formatters (from formatters.js)
        getJPDayName: 'writable',
        getENDayName: 'writable',
        formatISOWeekKey: 'writable',
        formatDateRangeDisplay: 'writable',
        // Calculations (from calculations.js)
        calculateWeekTotal: 'writable',
        calculateWeekProgress: 'writable',
        renderChart: 'writable',
        drawWeeklyChart: 'writable',
        renderExportButton: 'writable',
        exportAllData: 'writable',
        importData: 'writable',
        clearAllData: 'writable',
        loadSampleData: 'writable',
        loadData: 'writable',
        // CommonJS global used in some files
        module: 'writable',
      },
    },
    rules: {
      // ESLint recommended rules (manually specified since we can't import @eslint/js)
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-new-symbol': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'off', // Disabled to allow global function declarations
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': [
        'error',
        {
          varsIgnorePattern:
            '^(getDayLog|saveDayLog|deleteDayLog|getDayLogsByWeek|getAllDayLogs|getWeekTarget|saveWeekTarget|deleteWeekTarget|getAllWeekTargets|getISOWeekInfo|formatDateLocal|parseDateLocal|calculateWeekTotal|calculateWeekProgress|drawWeeklyChart|loadData|getJPDayName|getENDayName|formatISOWeekKey|formatDateRangeDisplay|DAY_NAMES_JP|DAY_NAMES_EN|DAY_LABELS_CHART|DAY_NAME_JP_TO_EN|MS_PER_WEEK|MS_PER_DAY|MAX_DAYS_HISTORY|CHART_PADDING|CHART_BAR_WIDTH_RATIO|Y_AXIS_CONFIG|CHART_GRID_LINES|ELEVATION_INPUT|WEEKLY_TARGET_INPUT|BACKUP_CONFIG|ISO_YEAR_RANGE|ISO_WEEK_RANGE)$',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
  // Tests use ESM imports — treat test files as modules for parsing
  {
    // Treat test and e2e files and common config files as ES modules
    files: [
      'test/**/*.js',
      'test/*.js',
      'e2e/**/*.js',
      'e2e/*.js',
      'playwright.config.js',
      'vitest.config.js',
    ],
    languageOptions: {
      sourceType: 'module',
      globals: {
        process: 'readonly',
      },
    },
  },
];
